=== bpkopania/projekt-hih-i-wai/xml/dane.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="sailing">
    <xs:complexType>
      <xs:sequence>
        
        
        <xs:element name ="history">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="historyEra" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="title" type="longStringType"/>
                    <xs:element name="descryption" type="xs:string"/>
                    <xs:element ref="asidePhoto" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute name="name" type="shortStringType"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>


        <xs:element name="sense">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="image" type="imageType" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="video" type="videoType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="licenses">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="howto">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="descryption"/>
                    <xs:element ref="asidePhoto" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="typesOfLicenses">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="license" type="licenseType" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!--GlobalTypes-->

  <xs:simpleType name="shortStringType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="30"/>
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="longStringType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="70"/>
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="imageType">
    <xs:simpleContent>
      <xs:extension base="shortStringType">
        <xs:attribute name="src" type="xs:anyURI"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="videoType">
    <xs:simpleContent>
      <xs:extension base="longStringType">
        <xs:attribute name="src" type="xs:anyURI"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="asidePhotoType">
    <xs:sequence>
      <xs:element name="image" type="imageType"/>
      <xs:element name="description" type="longStringType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="ageType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="120"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="licenseType">
    <xs:sequence>
      <xs:element name="age" type="ageType"/>
      <xs:element name="hours"/>
      <xs:element name="qualification" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="shortStringType"/>
  </xs:complexType>
  
  <!--globbalne elementy-->

  <xs:element name="asidePhoto" type="asidePhotoType"/>
  
</xs:schema>

=== bpkopania/projekt-hih-i-wai/xml/dane.xml
<?xml version="1.0" encoding="utf-8"?>
<sailing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dane.xsd">
  <history>
    <historyEra name="Introduction">
      <title>Żeglarstwo oraz jego krótka historia</title>
      <descryption>
        Ludzie od zarania dziejów są chłonni poznawania świata. Jednak wody morskie i oceaniczne były dla nich wielką przeszkodą. Początkowo siłą własnych mięśni pokonywali akweny. Czy to wpław czy przy użyciu łodzi z wiosłami.
        Z czasem zamontowano na masztach żagiel. Od tamtej pory ludzie dużo łatwiej poruszali się po wodach. Umożliwiło to spływ zbóż czy materiałów budowalnych rzekami lub innymi akwenami.
      </descryption>
    </historyEra>
    <historyEra name="Ancient">
      <title>Starożytna Grecja i Rzym</title>
      <descryption>
        Wraz z rozwojem cywilizacji statki zaczęły rosnąć oraz zaczęto wymyślać nowe typy ożaglowania. W Starożytnej Grecji, Rzymie oraz Egipcie żaglowce były używane do handlu na terenie Morza Śródziemnego.
        Ale nie tylko...
        Ludzie wykorzystali statki także do walki. Narody zaczęły ze sobą walczyć teraz także na morzach, wykorzystali je do transportu wojsk na teren walk, chociażby tak jak Grecy pod Troję czy Persowie podczas ataku na Grecję.
        Własnie w tamtym okresie powstała większość znanych nam do dzisiaj typów żagli.
      </descryption>
      <asidePhoto>
        <image src="/img/trireme.jpg">Triera</image>
        <description>Triera - grecki statek wojenny</description>
      </asidePhoto>
    </historyEra>
    <historyEra name="Discovery era">
      <title>Początek ery wielkich odkryć geograficznych</title>
      <descryption>
        Kraje półwyspu Iberyjskiego potrzebowały odpowiedzi co znajduje się za ich bezkresem oceanu - tak jak inne morza mają jakiś ląd po drugiej stronie tak też i oni zakładali, że za oceanem kryje się jakiś ląd.
        Początkowo zakładali, że znajdą tam Indie - czyli opłyną cały świat.
        Specjalnie do tego zadania przygotowywali swoje statki, w ten sposób powstała karawela. Łączyła ona zalety obu wówczas najpopularniejszych typów statków. Żagle prostokątne i trójkątne zwiększały prędkość statku, nie ograniczając go do kieruku wiatru. Drugim elementem jest ster centralny - zapewnia on żaglowcowi duża stabilność
        W 1492 r. Krzysztof Kolumb wraz z Amerigo Vespuccim odkryli nowy ląd. Załozyli, że to własnie Indie, wiec nazwali miejscową ludność Indianami. Jednak jakiś czas później Amerigo dowiódł, że to nowy kontynent - Nowy Świat, na jego cześć nazwany Ameryką.
      </descryption>
      <asidePhoto>
        <image src="/img/santa_maria.jpg">Karawela</image>
        <description>Karawela Santa Maria</description>
      </asidePhoto>
    </historyEra>
    <historyEra name="Trade Era">
      <title>Panowanie Europy nad całym światem</title>
      <descryption>
        Wraz ze wzorstem potęgi państw statego kontynentu, rosło zapotrzebowanie na handel morski z koloniami. Statki musiały być pojemniejsze, szybsze. To wtedy pojawiły się złote floty, które przewoziły cenne surowce między koloniami oraz do państwa europjeskiego.
        To własnie w tamtym miały miejsce pierwsze regaty. By przypłynąć z Indii do Europy potrzebny był korzystny wiatr monsunowy, który zmienia się co 6 miesięcy. Więc statki przypływały na stary kontynent falami. Ten który przypłynął szybciej, mógł mieć większe ceny produktów. Jak konkurencja przypływała to ceny zaczynały maleć. Statki, które pozwalały na to, nazwywały się kliprami.
      </descryption>
      <asidePhoto>
        <image src="/img/kliper.jpg">Kliper</image>
        <description>Kliper z XVII w. z rozłożonymi skrzydłami</description>
      </asidePhoto>
    </historyEra>
  </history>
</sailing>
